(**************************************************************************)
(*                                                                        *)
(*                                 OCaml                                  *)
(*                                                                        *)
(*                Ulysse Gérard, Thomas Refis, Frederic Bour,             *)
(*                           Xavier Van de Woestyne                       *)
(*                                                                        *)
(*   Copyright 2025 Tarides                                               *)
(*                                                                        *)
(*   All rights reserved.  This file is distributed under the terms of    *)
(*   the GNU Lesser General Public License version 2.1, with the          *)
(*   special exception on linking described in the file LICENSE.          *)
(*                                                                        *)
(**************************************************************************)

(** Returns a reference initially set to false that will be set to true
    when a type error is raised. *)
val monitor_errors : unit -> bool ref

(** Raise an error that can be caught: normal flow is resumed if a
    [catch_errors] handler was installed. *)
val raise_error : exn -> unit
[@@deprecated "use [log_and_raise] or [log_or_raise] instead"]

val log_and_raise : exn -> 'a

val log_or_raise : exn -> unit

(** Any [raise_error] invoked inside catch_errors will be added to
    the list. *)
val catch_errors : Warnings.state -> exn list ref -> (unit -> 'a) -> 'a

(* Keep track of type variables generated by error recovery. *)

val erroneous_type_register : Types.type_expr -> unit
val erroneous_type_check : Types.type_expr -> bool
val erroneous_expr_check : Typedtree.expression -> bool


(** Extend the given attributes with an incorrect attribute and the
    saved types after turning them into attributes *)
val recovery_attributes : Parsetree.attributes -> Parsetree.attributes

val with_warning_attribute :
  ?warning_attribute:Parsetree.attributes -> (unit -> 'b) -> 'b

val with_saved_types :
  ?save_part:('a -> Cmt_format.binary_part) -> (unit -> 'a) -> 'a

module Error_set : Set.S with type elt = Location.error
