(**************************************************************************)
(*                                                                        *)
(*                                 OCaml                                  *)
(*                                                                        *)
(*                Ulysse Gérard, Thomas Refis, Frederic Bour,             *)
(*                           Xavier Van de Woestyne                       *)
(*                                                                        *)
(*   Copyright 2025 Tarides                                               *)
(*                                                                        *)
(*   All rights reserved.  This file is distributed under the terms of    *)
(*   the GNU Lesser General Public License version 2.1, with the          *)
(*   special exception on linking described in the file LICENSE.          *)
(*                                                                        *)
(**************************************************************************)

(** Returns a reference initially set to false that will be set to true
    when a type error is raised. *)
val monitor_errors : unit -> bool ref

val raise_error : exn -> unit
[@@deprecated "use [log_and_raise] or [log_or_raise] instead"]

(** Logs the given exception if called from under a [catch_errors], otherwise
    raises it *)
val log_or_raise : exn -> unit

(** Logs the given exception if called from under a [catch_errors], and then
    raises it. *)
val log_and_raise : exn -> 'a

(* FIXME: should not mess with [Warnings.state] *)
(** [catch_error ws errors_log f] gathers all the errors logged by [f ()] into
    [errors_log]. *)
val catch_errors : Warnings.state -> exn list ref -> (unit -> 'a) -> 'a

(** [uncatch_errors f] disables logging in f, turning both [log_or_raise] and
    [log_and_raise] into [raise]. *)
val uncatch_errors : (unit -> 'a) -> 'a

(* Keep track of type variables generated by error recovery. *)

val erroneous_type_register : Types.type_expr -> unit
val erroneous_type_check : Types.type_expr -> bool
val erroneous_expr_check : Typedtree.expression -> bool


val with_warning_attribute :
  ?warning_attribute:Parsetree.attributes -> (unit -> 'b) -> 'b

module Error_set : Set.S with type elt = Location.error
